name: "Deploy"

on:
  push:
    tags:
      - 'v*'  # 只有在推送以 v 开头的标签（如 v1.0）时才会触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: astralapp/uv:python3.12-bookworm-slim
    
    # 发布 Release 必须赋予这行写权限
    permissions:
      contents: write 
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4  
        
      - name: Install dependencies
        run: uv sync
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true # 自动生成更新日志